### ISSUE TITLE
Gather and write down issues from Lansing data collection

### ISSUE THREAD

**Issue by glopesdev** [emotional-cities/pluma-experiments#42]
- [x] emotional-cities/pluma-experiments#38
- [x] emotional-cities/pluma-experiments#37
- [x] emotional-cities/pluma-experiments#36
- [x] emotional-cities/pluma-experiments#35
- [x] emotional-cities/pluma-experiments#34
- [x] emotional-cities/pluma-experiments#33
- [x] emotional-cities/pluma-experiments#32
- [x] emotional-cities/pluma-experiments#31
- [x] emotional-cities/pluma-experiments#30

**Comment by aspaNeuro** [comment]
All tasks are done.
