### ISSUE TITLE
eMOTIONAL Cities WP5

### ISSUE THREAD

**Issue by glopesdev** [emotional-cities/pluma-experiments#43]
Meta-issue to track ongoing development tasks.

- [ ] #57
- [x] ~Rename pluma-experiments repo to pluma-outdoor~
- [x] Create pluma-vr repo
- [x] Add new pluma board to the system
- [x] Finalize connectors for the new shell
- [x] Run hardware benchmarks on the new shell
- [x] Run outdoor walk with the new shell
- [x] emotional-cities/pluma-experiments#40
- [x] ~Publish Zyre package~ (turned into [EmotionalCities.Pupil](https://www.nuget.org/packages/EmotionalCities.Pupil/0.1.0-rc4))
- [x] Publish Pluma harp package ([EmotionalCities.Pluma](https://www.nuget.org/packages/EmotionalCities.Pluma))
- [x] emotional-cities/pluma#17
- [x] emotional-cities/pluma#18
- [x] #97
- [ ] emotional-cities/pluma-experiments#41
- [ ] Review SDI ingestion pipeline
- [ ] Review dataset folder structure
- [x] emotional-cities/pluma-experiments#42
- [x] emotional-cities/pluma-experiments#39
- [ ] emotional-cities/pluma-experiments#29
- [ ] #46
- [ ] #51 
- [ ] #52
- [x] #53 

## Issues from Lansing

- [x] emotional-cities/pluma-experiments#38
- [x] emotional-cities/pluma-experiments#37
- [x] emotional-cities/pluma-experiments#36
- [x] emotional-cities/pluma-experiments#35
- [x] emotional-cities/pluma-experiments#34
- [x] emotional-cities/pluma-experiments#33
- [x] emotional-cities/pluma-experiments#32
- [x] emotional-cities/pluma-experiments#31
- [x] emotional-cities/pluma-experiments#30
